"""Add page model

Revision ID: 468d47a25265
Revises:
Create Date: 2026-09-03 15:45:09.879921

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "468d47a25265"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pages_slug"), ["slug"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pages_slug"))

    op.drop_table("pages")
    # ### end Alembic commands ###
