"""Renaming Page to Post

Revision ID: 7781225ad29b
Revises: 468d47a25265
Create Date: 2026-09-04 09:20:16.240929

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7781225ad29b"
down_revision = "468d47a25265"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts",
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_posts_slug"), ["slug"], unique=True)

    with op.batch_alter_table("pages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pages_slug"))

    op.drop_table("pages")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pages",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("slug", sa.VARCHAR(length=80), nullable=False),
        sa.Column("title", sa.VARCHAR(length=120), nullable=False),
        sa.Column("body", sa.TEXT(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pages_slug"), ["slug"], unique=1)

    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_posts_slug"))

    op.drop_table("posts")
    # ### end Alembic commands ###
